In [21]:
import numpy as np
from scipy import sparse

In [22]:
# Creating a Vector
vector = np.array([1, 2, 3, 4, 5, 6])
vector_a = np.array([1,2,3])
vector_b = np.array([4,5,6])
# Creating a matrix
matrix = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
matrix_a = np.array([[1, 1, 1],[1, 1, 1],[1, 1, 2]])
matrix_b = np.array([[1, 3, 1],[1, 3, 1],[1, 3, 8]])

In [23]:
# Creating a sparse matrix
matrix_sparse = sparse.csc_matrix(matrix)
print(matrix_sparse)
matrix_large = np.array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
[3, 0, 0, 0, 0, 0, 0, 0, 0, 0]])
# Create compressed sparse row (CSR) matrix
matrix_large_sparse = sparse.csr_matrix(matrix_large)

# View larger sparse matrix
print(matrix_large_sparse)

<Compressed Sparse Column sparse matrix of dtype 'int64'
	with 9 stored elements and shape (3, 3)>
  Coords	Values
  (0, 0)	1
  (1, 0)	4
  (2, 0)	7
  (0, 1)	2
  (1, 1)	5
  (2, 1)	8
  (0, 2)	3
  (1, 2)	6
  (2, 2)	9
<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 2 stored elements and shape (3, 10)>
  Coords	Values
  (1, 1)	1
  (2, 0)	3


In [24]:
# Preallocating numpy arrays
zeros_vector = np.zeros(shape=5)
print(zeros_vector)
ones_matrix = np.full(shape=(3,3), fill_value=1)
print(ones_matrix)

[0. 0. 0. 0. 0.]
[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [25]:
# Selecting elements
# Select third element of vector
vector[2]
# Select second row, second column
matrix[1,1]
# Select all elements of a vector
vector[:]
# Select everything up to and including the third element
vector[:3]
# Select everything after the third element
vector[3:]
# Select the last element
vector[-1]
# Reverse the vector
vector[::-1]
# Select the first two rows and all columns of a matrix
matrix[:2,:]
# Select all rows and the second column
matrix[:,1:2]

array([[2],
       [5],
       [8]])

In [26]:
# Describing a matrix

print(f"The matrix shape is {matrix.shape}")
print(f"The size of the matrix is {matrix.size}")
print(f"The number of dimensions is {matrix.ndim}")


The matrix shape is (3, 3)
The size of the matrix is 9
The number of dimensions is 2


In [27]:
# Applying Functions over Each Element
add_100 = lambda i: i+100
vectorized_add_100 = np.vectorize(add_100)
vectorized_add_100 = vectorized_add_100(matrix)
print(f"The matrix {matrix}")
print(f"Vectorized matrix {vectorized_add_100}")

The matrix [[1 2 3]
 [4 5 6]
 [7 8 9]]
Vectorized matrix [[101 102 103]
 [104 105 106]
 [107 108 109]]


In [28]:
# Maximum and minimum Values
print(f"Max element is {np.max(matrix)}")
print(f"Min element is {np.min(matrix)}")

Max element is 9
Min element is 1


In [29]:
# Calculating the Average, Variance, and Standard Deviation
print(f"The mean is {np.mean(matrix)}")
print(f"The variance is {np.var(matrix)}")
print(f"The standard deviation is {np.std(matrix)}")
print(f"The mean value in each column is {np.mean(matrix, axis=0)}")
print(f"The mean value in each row is {np.mean(matrix, axis=1)}")

The mean is 5.0
The variance is 6.666666666666667
The standard deviation is 2.581988897471611
The mean value in each column is [4. 5. 6.]
The mean value in each row is [2. 5. 8.]


In [30]:
# Reshaping Arrays
# print(f"The matrix {matrix} is reshaped to {matrix.reshape(2, 3)}")
print(f"The matrix {matrix} is reshaped to {matrix.reshape(1, -1)}")
print(f"The matrix {matrix} is reshaped to {matrix.reshape(9)}")


The matrix [[1 2 3]
 [4 5 6]
 [7 8 9]] is reshaped to [[1 2 3 4 5 6 7 8 9]]
The matrix [[1 2 3]
 [4 5 6]
 [7 8 9]] is reshaped to [1 2 3 4 5 6 7 8 9]


In [31]:
# Transposing a vector or matrix
print(f"The transpose of matrix {matrix} is {matrix.T}")
print(f"The transpose of vector {vector} is {vector.T}")

The transpose of matrix [[1 2 3]
 [4 5 6]
 [7 8 9]] is [[1 4 7]
 [2 5 8]
 [3 6 9]]
The transpose of vector [1 2 3 4 5 6] is [1 2 3 4 5 6]


In [32]:
# Flattening a matrix - transform a matrix to 1-D Array
matrix.flatten()
np.ravel(matrix)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
# Matrix Rank
print(f"The matrix Rank is {np.linalg.matrix_rank(matrix)}")

The matrix Rank is 2


In [34]:
# Getting diagonal elements of matrix
matrix.diagonal()
matrix.diagonal(offset=-1)

array([4, 8])

In [35]:
# Trace of a matrix - the sum of the diagonal elements
matrix.trace()

np.int64(15)

In [36]:
# Calculating Dot Products
np.dot(vector_a, vector_b)
vector_a@vector_b

np.int64(32)

In [37]:
# Adding, subtracting and multiplying matrices
print(np.add(matrix_a, matrix_b))
print(np.subtract(matrix_a, matrix_b))
print(matrix_a*matrix_b)

[[ 2  4  2]
 [ 2  4  2]
 [ 2  4 10]]
[[ 0 -2  0]
 [ 0 -2  0]
 [ 0 -2 -6]]
[[ 1  3  1]
 [ 1  3  1]
 [ 1  3 16]]


In [38]:
# Inverting a Matrix
np.linalg.inv(matrix)

array([[-4.50359963e+15,  9.00719925e+15, -4.50359963e+15],
       [ 9.00719925e+15, -1.80143985e+16,  9.00719925e+15],
       [-4.50359963e+15,  9.00719925e+15, -4.50359963e+15]])

In [39]:
# Generating Random Values - pseudorandom values.
np.random.seed(0)
np.random.random(3)
# Generate three random integers between 0 and 10
np.random.randint(0, 11, 3)
# Draw three numbers from a normal distribution with mean 0.0 and standard deviation of 1.0
np.random.normal(0.0, 1.0, 3)
# Draw three numbers from a logistic distribution with mean 0.0 and scale of 1.0
np.random.logistic(0.0, 1.0, 3)
# Draw three numbers greater than or equal to 1.0 and less than 2.0
np.random.uniform(1.0, 2.0, 3)

array([1.47997717, 1.3927848 , 1.83607876])